apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: futbolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
`         image: fra.ocir.io/frwqejk9in9h/futbolin/futbolin-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
              name: https
          env:
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: webapp-oidc
                  key: oidc.client.id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp-oidc
                  key: oidc.client.secret
            - name: CLIENT_KEYSTORE_FILE
              value: /tmp/keystore.p12
            - name: CLIENT_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp-oidc
                  key: oidc.keystore.password
            - name: OIDC_RPHOSTANDPORT
              value: https://futbolin.mulders.it/
      volumes:
      - name: client-keystore
        secret:
          secretName: webapp-oidc
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: futbolin
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 9443
    targetPort: 9443
  selector:
    app: webapp

