name: Deploy application

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: |
          echo Running a test job