name: Deploy application

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: |
          echo Running a test job